### ISSUE TITLE
Grid view album listing

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/VocaDB-App#10]
Grid/Tiles -type album listing would great.

**Comment by up2code** [comment]
Not sure which page, but this is what I changed. https://github.com/VocaDB/VocaDB-App/commit/6f9e2a91be4c764e4d96764a8ebdf28b66c6c626

## Artist detail
![screenshot at mar 27 00-12-15](https://user-images.githubusercontent.com/2321626/37921587-6f63fa7c-3154-11e8-9411-3934c6b477b3.png)

## Song detail
![screenshot at mar 27 00-13-14](https://user-images.githubusercontent.com/2321626/37921668-ab6cfb22-3154-11e8-816d-1b8d94fb3a26.png)
