### ISSUE TITLE
Null date displayed for events with unknown date

### ISSUE THREAD

**Issue by Nefere256** [VocaDB/VocaDB-App#100]
If a date isn't specified for an event, the "null" text is displayed on an event list. The date should be omitted in this case.

Few examples: [COMIC1](https://touhoudb.com/E/139/comic1-1), [Cafe Terrace 2](https://touhoudb.com/E/187/kagaku-seiki-no-caf-terrace-2)

Screenshots:
![t3](https://user-images.githubusercontent.com/46942248/68991831-80911e00-0863-11ea-9a20-aa70335d5ce6.png)
![t4](https://user-images.githubusercontent.com/46942248/68991841-90106700-0863-11ea-9920-ab23be93cd0e.png)

Device: Xiaomi Redmi 4A
OS: Android 7.1.2 N2G47H (MIUI Global 10.2.3)
App version: 3.0.1

**Comment by up2code** [comment]
Fixed in 94732d166d8ab82b6b41e3afde7eb12d04a0ab30. Wait for deploy next release.

**Comment by up2code** [comment]
Done in v3.0.2
