### ISSUE TITLE
Event series

### ISSUE THREAD

**Issue by riipah** [VocaDB/VocaDB-App#103]
Would be a good idea if there was a link from event page to event series. For example Miku Expo.

**Comment by up2code** [comment]
Currently I can't find api to fetch event series detail by id. or should I use content from `/api/releaseEvents/{id}`? But this way will lack some detail info such as weblinks.

**Comment by riipah** [comment]
Hmm yeah you're right there's no API for that yet, but it's easy to add.

**Comment by riipah** [comment]
The API is now implemented, by @ycanardeau

**Comment by up2code** [comment]
Could you update to TouhouDB too? For now I'll submit VocaDB for apple review first. TouhouDB will be later after API available.

**Comment by riipah** [comment]
Deployed on TouhouDB too.
