### ISSUE TITLE
Comments about song search / filtering

### ISSUE THREAD

**Issue by riipah** [VocaDB/VocaDB-App#12]
* I think the "status" filter could be removed. It's mostly used to find entries that need work, but no one is going to do edits on the phone anyway, so it should be redundant on the mobile app.

* For sort, you can leave out empty and "none" options. The default should be "name".

* For tags, you might want to filter by "genres" category (same as website). The full list of top tags includes a lot of nonsense. Also, I added option to limit the number of top tags to return. I think displaying top 5 tags in the mobile app is enough.

* A custom filter for tags (similar to artists list) would be useful too.

* Perhaps consider adding filtering for minimum rating score, to get popular songs.

Otherwise I really like the filtering options :)

**Comment by up2code** [comment]
Thanks! and here after fixed as your suggestion. For tags, I had remove all default tags and let user can search & add tags by their own.
![screenshot_2018-04-07-15-09-29-215_com vocadb app](https://user-images.githubusercontent.com/2321626/38452849-75388118-3a76-11e8-8d8e-8ac7bb12f080.png)

**Comment by riipah** [comment]
Yeah, I think this can be closed?
