### ISSUE TITLE
Feature suggestion: Export user data to csv or similar

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/VocaDB-App#57]
Since the user data is not tied to the VocaDB back end (the data is saved client-side), it would be good to have a way to save the user data (followed artists/liked songs) for back-up purposes.

**Comment by up2code** [comment]
I had thought about this too. Maybe export/import as JSON file will be more easier for handle data. Or integrate with cloud database such as Firebase for handle temporary users.
