### ISSUE TITLE
App has been removed from Play store by Google due to a policy violation

### ISSUE THREAD

**Issue by up2code** [VocaDB/VocaDB-App#82]
![play_removed](https://user-images.githubusercontent.com/2321626/53616109-bb8aed00-3c13-11e9-8561-6899a85ce9fd.png)

Need to investigate and contact to Google's policy support team for more information about which one I had violated. Not sure is about I had used embed youtube video inside app instead of using Youtube API.

**Comment by riipah** [comment]
Huh that is certainly odd. Glad I'm not in mobile development business

**Comment by up2code** [comment]
**Update progress**

I had read [Youtube Terms of Service](https://www.youtube.com/t/terms) but still not sure which one that I had violated. At section 4 seem like most posibility, But this app didn't made for commercial usage and I didn't modified anything about Embeddable Player.

I had sent an appeal and ask for more detail to Google play policy team. Wait for them to reply.

![google_appeal](https://user-images.githubusercontent.com/2321626/53675052-5d1e4700-3cc5-11e9-8d31-5c2544ca3784.png)

**Comment by up2code** [comment]
**Update progress 2**

Google Play Team had replied my appeal. 

Seem like Youtube not allow you to run their videos in background. There are some solutions found out in [stackoverflow](https://stackoverflow.com/questions/36382935/how-to-prevent-react-native-android-webview-from-running-youtube-in-the-backgrou) about this issue. 

I don't know why but in my device (Huewei P20) Youtube is not working on background when I try to play and switch to home but not sure about other device.

Anyway I'll try to fix it and resubmit app.

![google_play_response](https://user-images.githubusercontent.com/2321626/53709125-2da83f80-3e69-11e9-8efb-463bdb179362.png)

Still don't understand what or how related about this screenshot from them to Youtube background playing.

![0-5847000025436](https://user-images.githubusercontent.com/2321626/53709353-6dbbf200-3e6a-11e9-8641-3ae72a973434.png)

**Comment by up2code** [comment]
I had resubmit app and already published to Play store. I don't know if they had reviewed yet since no any response from them. So I'll close this issue for now.
