### ISSUE TITLE
Unable to play PV for android version Kitkat and below (below API level 20)

### ISSUE THREAD

**Issue by up2code** [VocaDB/VocaDB-App#87]
VocaDB app support minimum API level 16 (4.1.x Jelly Bean) but plugin [youtube_player_flutter ](https://pub.dev/packages/youtube_player_flutter) support minimum at API level 20 (Lollipop and higher)

There is another plugin [youtube_player ](https://pub.dev/packages/youtube_player)that support API level 16 and below. I need to test and validate player to switch plugin depend on android version of user.

**Comment by riipah** [comment]
I think at this point you could just increase the minimum API level to 20. I mean, they've released Android 10 already.

**Comment by up2code** [comment]
I just checked on app statistics. There are few active users who using on Android 4.2 and lower version. It's not hard to coding but problem is I don't have physical device with low version to test (It seems like emulator not work well for testing video)

Increase minimum API level to 20 is another solution too because I think Jelly Bean is really old now.

![PjPDsxk (1)](https://user-images.githubusercontent.com/2321626/66728759-173b7b00-ee71-11e9-8fc0-9151bac7e47d.png)

**Comment by up2code** [comment]
I had change minimum api to 20 because limitation of webview_flutter (Plugin from Flutter team that in Developer preview state) that is behind youtube_player_flutter plugin.
