### ISSUE TITLE
Access search from anywhere

### ISSUE THREAD

**Issue by riipah** [VocaDB/VocaDB-App#92]
I would like to have access to search page from anywhere. Seems to be only front page now. 

Link to front page from any page would be good too.

**Comment by up2code** [comment]
Currently I can't find any widget for display and quickly access from anywhere. Even FAB need to specific on each page.

![sample_menu](https://user-images.githubusercontent.com/2321626/68079764-6564ee00-fe21-11e9-803f-d0edb6d5bcb4.png)

Only idea I have right now is add action buttons for each detail page for quickly return to first page or access universal search page.

**Comment by riipah** [comment]
Uhh, I'm not sure what all that means. Link to front page is better than nothing, but I think we would want to have quick access to search on every page eventually. Personally I consider that one of the most important features on the website.

**Comment by up2code** [comment]
I had added in version 3.0.1 with action button search and home on every page.
Let me know if is okay or any part is missing.
