### ISSUE TITLE
Not specified event type for series event

### ISSUE THREAD

**Issue by Nefere256** [VocaDB/VocaDB-App#99]
A lot of events is with not specified event type in the app even if only 10-20 events out of 700+ are with truly unspecified type.

Only standalone events or events which were standalone in the past (for example [first CODE-G club](https://touhoudb.com/E/267/code-g---midnight-toho-music-p)) have an event type displayed. Filtering by event type seems fine.

Upcoming events section:
![t1](https://user-images.githubusercontent.com/46942248/68991638-f5af2400-0860-11ea-962c-b34f7a38f1d4.png)

All events:
![t2](https://user-images.githubusercontent.com/46942248/68991770-889c8e00-0862-11ea-955e-92ef7ed37f49.png)

Filter events by club type results:
![t5](https://user-images.githubusercontent.com/46942248/68991709-dc5aa780-0861-11ea-8749-cbf7e228115b.png)

Device: Xiaomi Redmi 4A
OS: Android 7.1.2 N2G47H (MIUI Global 10.2.3)
App version: 3.0.1 (appears in 3.0.0 too)

**Comment by riipah** [comment]
On the website, the event type is inherited from series. I'm guessing the app isn't doing that right now.

**Comment by up2code** [comment]
@riipah So I need to use category from series if it exists, or else using default category field right?

**Comment by riipah** [comment]
Yes. If there's a series, then category cannot be set for event currently.

**Comment by up2code** [comment]
Done in v3.0.2
